package:
  name: conda-index-pkg-a
  version: "1.0"

source:
   git_url: https://github.com/kalefranz/conda-test-packages.git
   git_rev: master

build:
  number: 0
  # noarch: python
  script: python conda-index-pkg-a/setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - conda-index-pkg-a = conda_index_pkg_a:main
    - conda-index-pkg-a-helper = conda_index_pkg_a:helper

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - conda_index_pkg_a
  commands:
    - conda-index-pkg-a

about:
  home: https://anaconda.org/conda-test/conda-index-pkg-a
  license: BSD
  license_file: LICENSE
  summary: Summary field for conda-index-pkg-a
  description: |
    Description field for conda-index-pkg-a. Actually, this is just the python description.
    Python is a widely used high-level, general-purpose, interpreted, dynamic
    programming language. Its design philosophy emphasizes code
    readability, and its syntax allows programmers to express concepts in
    fewer lines of code than would be possible in languages such as C++ or
    Java. The language provides constructs intended to enable clear programs
    on both a small and large scale.
  doc_url: https://github.com/kalefranz/conda-test-packages/blob/master/conda-index-pkg-a
  doc_source_url: https://github.com/kalefranz/conda-test-packages/blob/master/conda-index-pkg-a/README.md
  dev_url: https://github.com/kalefranz/conda-test-packages/blob/master/conda-index-pkg-a/meta.yaml
